# These are supported funding model platforms

github: [svaksha]
patreon: svaksha
open_collective: svaksha
ko_fi: svaksha
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: svaksha
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: https://liberapay.com/svaksha/
